### ISSUE TITLE
Get cell (AKCollectionViewCell)

### ISSUE THREAD

**Issue by jathu** [Akkyie/AKPickerView-Swift#12]
Is there a reason why a AKCollectionViewCell is not accessible through any methods?

**Comment by akkyie** [comment]
@jathu It is simply because AKPickerView is a horizontal version of UIPickerView (originally) and it doesn't allow us to access its internal cells. But I'm currently working on making AKPickerView view-based and providing interfaces to access it. You will be able to customize your picker using it, but I'm sorry for my lazy progress.

**Comment by jathu** [comment]
That's cool, I initially wanted to access each cell so I can scroll with the selection being on the left. However I came up with the alternative (better) solution here https://github.com/Akkyie/AKPickerView-Swift/issues/3
