### ISSUE TITLE
AKPickerView.selectedItem is not public

### ISSUE THREAD

**Issue by csimmons0** [Akkyie/AKPickerView-Swift#29]
Did you mean to make the selectedItem field public? The comments suggest as much, and I'm not seeing another way to know which item is selected aside from an AKPickerViewDelegate, and that's overkill for me.

// MARK: Readonly Properties
/// Readonly. Index of currently selected item.
- private(set) var selectedItem: Int = 0
+ private(set) public var selectedItem: Int = 0

**Comment by rserentill** [comment]
I agree with @csimmons0. In fact, I think it would be interesting to make it public so you can set an option to be selected by default (I don't see a function to set the default option):
`// MARK: Readonly Properties`
`/// Readonly. Index of currently selected item.`
`- private(set) var selectedItem: Int = 0`
`+ public var selectedItem: Int = 0`

**Comment by akkyie** [comment]
Fixed. https://github.com/Akkyie/AKPickerView-Swift/pull/31
Setting `selectedItem` is still private because changing it without calling `selectItem` may cause a inconsistency.
You can call `selectItem:` in `viewDidLoad` or like to set the initially selected item.
Thank you for contributing, @csimmons0 and @rserentill !
